//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StudentsDuplexReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WcfExamples", ConfigurationName="StudentsDuplexReference.IStudentsDuplex", CallbackContract=typeof(Client.StudentsDuplexReference.IStudentsDuplexCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IStudentsDuplex {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfExamples/IStudentsDuplex/Login")]
        void Login(string greeting);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfExamples/IStudentsDuplex/Login")]
        System.Threading.Tasks.Task LoginAsync(string greeting);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentsDuplexCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfExamples/IStudentsDuplex/Receive")]
        void Receive(string response);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentsDuplexChannel : Client.StudentsDuplexReference.IStudentsDuplex, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsDuplexClient : System.ServiceModel.DuplexClientBase<Client.StudentsDuplexReference.IStudentsDuplex>, Client.StudentsDuplexReference.IStudentsDuplex {
        
        public StudentsDuplexClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public StudentsDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public StudentsDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsDuplexClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsDuplexClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string greeting) {
            base.Channel.Login(greeting);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string greeting) {
            return base.Channel.LoginAsync(greeting);
        }
    }
}
