//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18052
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfNetMeeting.MeetingServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="NetMeetingExample", ConfigurationName="MeetingServiceReference.IMeetingService")]
    public interface IMeetingService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/EnterRoom")]
        void EnterRoom(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/EnterRoom")]
        System.Threading.Tasks.Task EnterRoomAsync(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/Say")]
        void Say(string userName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/Say")]
        System.Threading.Tasks.Task SayAsync(string userName, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/ExitRoom")]
        void ExitRoom(string userName);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="NetMeetingExample/IMeetingService/ExitRoom")]
        System.Threading.Tasks.Task ExitRoomAsync(string userName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeetingServiceChannel : WcfNetMeeting.MeetingServiceReference.IMeetingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeetingServiceClient : System.ServiceModel.ClientBase<WcfNetMeeting.MeetingServiceReference.IMeetingService>, WcfNetMeeting.MeetingServiceReference.IMeetingService {
        
        public MeetingServiceClient() {
        }
        
        public MeetingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeetingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnterRoom(string userName) {
            base.Channel.EnterRoom(userName);
        }
        
        public System.Threading.Tasks.Task EnterRoomAsync(string userName) {
            return base.Channel.EnterRoomAsync(userName);
        }
        
        public void Say(string userName, string message) {
            base.Channel.Say(userName, message);
        }
        
        public System.Threading.Tasks.Task SayAsync(string userName, string message) {
            return base.Channel.SayAsync(userName, message);
        }
        
        public void ExitRoom(string userName) {
            base.Channel.ExitRoom(userName);
        }
        
        public System.Threading.Tasks.Task ExitRoomAsync(string userName) {
            return base.Channel.ExitRoomAsync(userName);
        }
    }
}
