//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesList
    {
        public int Id { get; set; }
        public string SaleId { get; set; }
        public string name { get; set; }
        public int num { get; set; }
        public double untiPrice { get; set; }
        public double price { get; set; }
        public string OperatorName { get; set; }
    }
}
