//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.StudentsOneWayReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/Service")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherInfo {
            get {
                return this.OtherInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherInfoField, value) != true)) {
                    this.OtherInfoField = value;
                    this.RaisePropertyChanged("OtherInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="WcfServiceExamples", ConfigurationName="StudentsOneWayReference.IStudentsOneWay")]
    public interface IStudentsOneWay {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Clear")]
        void Clear();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Clear")]
        System.Threading.Tasks.Task ClearAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Add")]
        void Add(Client.StudentsOneWayReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Add")]
        System.Threading.Tasks.Task AddAsync(Client.StudentsOneWayReference.Student student);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Remove")]
        void Remove(int studentID);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="WcfServiceExamples/IStudentsOneWay/Remove")]
        System.Threading.Tasks.Task RemoveAsync(int studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfServiceExamples/IStudentsOneWay/GetStudentsValue", ReplyAction="WcfServiceExamples/IStudentsOneWay/GetStudentsValueResponse")]
        string GetStudentsValue();
        
        [System.ServiceModel.OperationContractAttribute(Action="WcfServiceExamples/IStudentsOneWay/GetStudentsValue", ReplyAction="WcfServiceExamples/IStudentsOneWay/GetStudentsValueResponse")]
        System.Threading.Tasks.Task<string> GetStudentsValueAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentsOneWayChannel : Client.StudentsOneWayReference.IStudentsOneWay, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsOneWayClient : System.ServiceModel.ClientBase<Client.StudentsOneWayReference.IStudentsOneWay>, Client.StudentsOneWayReference.IStudentsOneWay {
        
        public StudentsOneWayClient() {
        }
        
        public StudentsOneWayClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentsOneWayClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsOneWayClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsOneWayClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Clear() {
            base.Channel.Clear();
        }
        
        public System.Threading.Tasks.Task ClearAsync() {
            return base.Channel.ClearAsync();
        }
        
        public void Add(Client.StudentsOneWayReference.Student student) {
            base.Channel.Add(student);
        }
        
        public System.Threading.Tasks.Task AddAsync(Client.StudentsOneWayReference.Student student) {
            return base.Channel.AddAsync(student);
        }
        
        public void Remove(int studentID) {
            base.Channel.Remove(studentID);
        }
        
        public System.Threading.Tasks.Task RemoveAsync(int studentID) {
            return base.Channel.RemoveAsync(studentID);
        }
        
        public string GetStudentsValue() {
            return base.Channel.GetStudentsValue();
        }
        
        public System.Threading.Tasks.Task<string> GetStudentsValueAsync() {
            return base.Channel.GetStudentsValueAsync();
        }
    }
}
